# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: General point run Scrapers

on:
  #  push:
  #    branches: [ main ]
  schedule:
    - cron: '00 04 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Add 'sites' folder to Python path
      run: |
        echo "export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/sites/" >> $GITHUB_ENV
    
    - name: List repository contents
      run: ls

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        sudo apt-get install curl
    - name: All scrapers runs
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python3 sites/script_runner.py
