on:
  schedule:
    - cron: '00 04 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Add Python Path
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install allure-pytest
        sudo apt-get install curl

    # - name: All scrapers run
    #   env:
    #     API_KEY: ${{ secrets.API_KEY }}
    #   run: |
    #     python3 sites/script_runner.py || true
    #     echo "Continuing despite potential failure..."
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Allure Command-Line
      run: |
        sudo apt-add-repository -y ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: Run pytest with HTML Allure Reporting
      continue-on-error: true
      run: |
        pytest -m regression -vv --alluredir=./allure-results
    
    - name: Compile the allure json files into a single html report
      run: allure generate --single-file

    - name: Move api_test_report_allure.html to docs folder
      run: mv -force "allure-report/index.html" "docs/api_test_report_allure.html"

    - name: Commit and push api_test_report_allure.html
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "docs/api_test_report_allure.html"
        git commit -m "Add pytest API HTML Allure Report"
        git push origin main


