name: General point run Scrapers

on:
  schedule:
    - cron: '00 04 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Add Python Path
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        sudo apt-get install curl
    - name: All scrapers runs
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python3 sites/script_runner.py || true
        echo "Continuing despite potential failure..."

    - name: Run pytest
      continue-on-error: true
      run: pytest -m regression -vv
