on:
  schedule:
    - cron: '00 04 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Add Python Path
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        sudo apt-get install curl

    - name: All scrapers run
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python3 sites/script_runner.py || true
        echo "Continuing despite potential failure..."

    - name: Run pytest with Allure reporting
      continue-on-error: true
      run: |
        pytest -m regression -vv --alluredir=allure-results

    - name: Move Allure results to docs folder
      run: mv allure-results "docs/allure-results"

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: docs/allure-results
        allure_history: docs/allure-history
        keep_reports: 20

    - name: Commit and push Allure report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "docs/allure-results" "docs/allure-history"
        git commit -m "Add Allure test report"
        git push origin main

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
